// Icons
import { Check, Close } from '@/components';

// Key
const key = new Date().toString();

export const weekSchedule = [
  [
    '5:00AM',
    <Check key={key} />,
    <Check key={key} />,
    <Check key={key} />,
    <Check key={key} />,
    <Check key={key} />,
    <Close key={key} />,
    <Close key={key} />,
  ],
  [
    '6:00AM',
    <Check key={key} />,
    <Check key={key} />,
    <Check key={key} />,
    <Check key={key} />,
    <Check key={key} />,
    <Close key={key} />,
    <Close key={key} />,
  ],
  [
    '7:00AM',
    <Check key={key} />,
    <Check key={key} />,
    <Check key={key} />,
    <Check key={key} />,
    <Check key={key} />,
    <Close key={key} />,
    <Close key={key} />,
  ],
  [
    '8:00AM',
    <Check key={key} />,
    <Check key={key} />,
    <Check key={key} />,
    <Check key={key} />,
    <Check key={key} />,
    <Close key={key} />,
    <Close key={key} />,
  ],
  [
    '9:00AM',
    <Check key={key} />,
    <Check key={key} />,
    <Check key={key} />,
    <Check key={key} />,
    <Check key={key} />,
    <Check key={key} />,
    <Close key={key} />,
  ],
  [
    '10:00AM',
    <Check key={key} />,
    <Check key={key} />,
    <Check key={key} />,
    <Check key={key} />,
    <Check key={key} />,
    <Check key={key} />,
    <Close key={key} />,
  ],
  [
    '4:00PM',
    <Check key={key} />,
    <Check key={key} />,
    <Check key={key} />,
    <Check key={key} />,
    <Check key={key} />,
    <Close key={key} />,
    <Close key={key} />,
  ],
  [
    '5:00PM',
    <Check key={key} />,
    <Check key={key} />,
    <Check key={key} />,
    <Check key={key} />,
    <Check key={key} />,
    <Close key={key} />,
    <Close key={key} />,
  ],
  [
    '6:00PM',
    <Check key={key} />,
    <Check key={key} />,
    <Check key={key} />,
    <Check key={key} />,
    <Check key={key} />,
    <Close key={key} />,
    <Close key={key} />,
  ],
  [
    '7:00PM',
    <Check key={key} />,
    <Check key={key} />,
    <Check key={key} />,
    <Check key={key} />,
    <Check key={key} />,
    <Close key={key} />,
    <Close key={key} />,
  ],
];
